LANGUAGE_CATEGORIES = {
    "San Diego Common Languages": {
        "english": "English",
        "spanish": "Spanish",
        "tagalog": "Tagalog",
        "chinese": "Chinese",
        "vietnamese": "Vietnamese",
        "korean": "Korean",
        "japanese": "Japanese",
        "khmer": "Khmer",
        "hmong": "Hmong",
        "thai": "Thai",
        "lao": "Lao"
    },
    "African Languages": {
        "amharic": "Amharic",
        "hausa": "Hausa",
        "igbo": "Igbo",
        "lingala": "Lingala",
        "oromo": "Oromo",
        "somali": "Somali",
        "swahili": "Swahili",
        "twi": "Twi",
        "wolof": "Wolof",
        "yoruba": "Yoruba",
        "zulu": "Zulu",
        "afrikaans": "Afrikaans",
        "bambara": "Bambara",
        "bemba": "Bemba",
        "chichewa": "Chichewa",
        "ganda": "Ganda",
        "kikuyu": "Kikuyu",
        "kinyarwanda": "Kinyarwanda",
        "luganda": "Luganda",
        "luo": "Luo",
        "makonde": "Makonde",
        "maltese": "Maltese",
        "mbumba": "Mbumba",
        "ndebele": "Ndebele",
        "nyanja": "Nyanja",
        "shona": "Shona",
        "swati": "Swati",
        "tswana": "Tswana",
        "venda": "Venda",
        "xhosa": "Xhosa"
    },
    "European Languages": {
        "bosnian": "Bosnian",
        "bulgarian": "Bulgarian",
        "croatian": "Croatian",
        "czech": "Czech",
        "danish": "Danish",
        "dutch": "Dutch",
        "finnish": "Finnish",
        "greek": "Greek",
        "french": "French",
        "german": "German",
        "italian": "Italian",
        "hungarian": "Hungarian",
        "norwegian": "Norwegian",
        "polish": "Polish",
        "romanian": "Romanian",
        "serbian": "Serbian",
        "swedish": "Swedish",
        "ukrainian": "Ukrainian",
        "albanian": "Albanian",
        "armenian": "Armenian",
        "azerbaijani": "Azerbaijani",
        "belarusian": "Belarusian",
        "estonian": "Estonian",
        "icelandic": "Icelandic",
        "irish": "Irish",
        "latvian": "Latvian",
        "lithuanian": "Lithuanian",
        "macedonian": "Macedonian",
        "moldovan": "Moldovan",
        "montenegrin": "Montenegrin",
        "portuguese": "Portuguese",
        "russian": "Russian",
        "slovak": "Slovak",
        "slovenian": "Slovenian"
    },
    "Asian Languages": {
        "burmese": "Burmese",
        "bengali": "Bengali",
        "mandarin": "Mandarin",
        "cantonese": "Cantonese",
        "gujarati": "Gujarati",
        "malay": "Malay",
        "punjabi": "Punjabi",
        "tamil": "Tamil",
        "telugu": "Telugu",
        "hindi": "Hindi",
        "indonesian": "Indonesian"
    },
    "Middle Eastern Languages": {
        "arabic": "Arabic",
        "hebrew": "Hebrew",
        "kurdish": "Kurdish",
        "armenian": "Armenian",
        "syriac": "Syriac",
        "pashto": "Pashto",
        "turkish": "Turkish",
        "urdu": "Urdu",
        "farsi": "Farsi"
    },
    "Indigenous American Languages": {
        "navajo": "Navajo",
        "quechua": "Quechua",
        "inuit": "Inuit",
        "apache": "Apache",
        "cherokee": "Cherokee",
        "chamorro": "Chamorro",
        "chickasaw": "Chickasaw",
        "choctaw": "Choctaw",
        "comanche": "Comanche",
        "cree": "Cree",
        "haida": "Haida",
        "haudenosaunee": "Haudenosaunee",
        "iroquois": "Iroquois",
        "kiowa": "Kiowa",
        "lakota": "Lakota",
        "maya": "Maya",
        "nahuatl": "Nahuatl",
        "pueblo": "Pueblo",
        "tlingit": "Tlingit",
        "turtle": "Turtle",
        "yaqui": "Yaqui",
        "zuni": "Zuni"
    },
    "Pacific Languages": {
        "hawaiian": "Hawaiian",
        "maori": "Maori",
        "samoan": "Samoan",
        "tahitian": "Tahitian",
        "tongan": "Tongan",
        "fijian": "Fijian"
    },
    "Supernatural & Ancient Languages": {
        "animal": "Animal",
        "spirit": "Spirit",
        "enochian": "Enochian",
        "old_english": "Old English",
        "old_norse": "Old Norse",
        "latin": "Latin",
        "ancient_greek": "Ancient Greek",
        "ancient_egyptian": "Ancient Egyptian",
        "akkadian": "Akkadian",
        "sanskrit": "Sanskrit",
        "babylonian": "Babylonian",
        "sumerian": "Sumerian",
        "elamite": "Elamite",
        "hittite": "Hittite",
        "phoenician": "Phoenician",
        "minoan": "Minoan",
        "mycenaean": "Mycenaean"
    }
}

# Create a flat dictionary of all available languages for quick lookup
AVAILABLE_LANGUAGES = {}
for category in LANGUAGE_CATEGORIES.values():
    AVAILABLE_LANGUAGES.update(category)
