"""
Language data for the Chronicles of Darkness language system.

This module contains the available languages that characters can learn
through the Language merit.
"""

AVAILABLE_LANGUAGES = {
    # Common Languages (most games will be in English-speaking areas)
    "english": "English",
    "spanish": "Spanish",
    "french": "French",
    "german": "German",
    "italian": "Italian",
    "portuguese": "Portuguese",
    
    # Asian Languages
    "mandarin": "Mandarin",
    "cantonese": "Cantonese",
    "japanese": "Japanese",
    "korean": "Korean",
    "vietnamese": "Vietnamese",
    "thai": "Thai",
    "tagalog": "Tagalog",
    "hindi": "Hindi",
    "bengali": "Bengali",
    "tamil": "Tamil",
    "telugu": "Telugu",
    "gujarati": "Gujarati",
    "punjabi": "Punjabi",
    "malay": "Malay",
    "indonesian": "Indonesian",
    "burmese": "Burmese",
    "khmer": "Khmer",
    "hmong": "Hmong",
    "lao": "Lao",
    
    # European Languages
    "russian": "Russian",
    "polish": "Polish",
    "ukrainian": "Ukrainian",
    "czech": "Czech",
    "romanian": "Romanian",
    "hungarian": "Hungarian",
    "greek": "Greek",
    "dutch": "Dutch",
    "swedish": "Swedish",
    "norwegian": "Norwegian",
    "danish": "Danish",
    "finnish": "Finnish",
    "icelandic": "Icelandic",
    "irish": "Irish",
    "croatian": "Croatian",
    "serbian": "Serbian",
    "bulgarian": "Bulgarian",
    "slovak": "Slovak",
    "slovenian": "Slovenian",
    "albanian": "Albanian",
    "estonian": "Estonian",
    "latvian": "Latvian",
    "lithuanian": "Lithuanian",
    "macedonian": "Macedonian",
    "bosnian": "Bosnian",
    "belarusian": "Belarusian",
    "moldovan": "Moldovan",
    "montenegrin": "Montenegrin",
    
    # Middle Eastern Languages
    "arabic": "Arabic",
    "hebrew": "Hebrew",
    "turkish": "Turkish",
    "farsi": "Farsi",
    "urdu": "Urdu",
    "kurdish": "Kurdish",
    "pashto": "Pashto",
    "armenian": "Armenian",
    "azerbaijani": "Azerbaijani",
    "syriac": "Syriac",
    
    # African Languages
    "swahili": "Swahili",
    "amharic": "Amharic",
    "hausa": "Hausa",
    "yoruba": "Yoruba",
    "igbo": "Igbo",
    "zulu": "Zulu",
    "xhosa": "Xhosa",
    "afrikaans": "Afrikaans",
    "somali": "Somali",
    "oromo": "Oromo",
    "lingala": "Lingala",
    "wolof": "Wolof",
    "twi": "Twi",
    "bambara": "Bambara",
    "bemba": "Bemba",
    "chichewa": "Chichewa",
    "ganda": "Ganda",
    "kikuyu": "Kikuyu",
    "kinyarwanda": "Kinyarwanda",
    "luganda": "Luganda",
    "luo": "Luo",
    "makonde": "Makonde",
    "mbumba": "Mbumba",
    "ndebele": "Ndebele",
    "nyanja": "Nyanja",
    "shona": "Shona",
    "swati": "Swati",
    "tswana": "Tswana",
    "venda": "Venda",
    
    # Indigenous American Languages
    "navajo": "Navajo",
    "quechua": "Quechua",
    "inuit": "Inuit",
    "apache": "Apache",
    "cherokee": "Cherokee",
    "chamorro": "Chamorro",
    "chickasaw": "Chickasaw",
    "choctaw": "Choctaw",
    "comanche": "Comanche",
    "cree": "Cree",
    "haida": "Haida",
    "haudenosaunee": "Haudenosaunee",
    "iroquois": "Iroquois",
    "kiowa": "Kiowa",
    "lakota": "Lakota",
    "maya": "Maya",
    "pueblo": "Pueblo",
    "tlingit": "Tlingit",
    "yaqui": "Yaqui",
    "zuni": "Zuni",
    
    # Pacific Languages
    "hawaiian": "Hawaiian",
    "maori": "Maori",
    "samoan": "Samoan",
    "tahitian": "Tahitian",
    "tongan": "Tongan",
    "fijian": "Fijian",
    
    # Ancient & Supernatural Languages
    "latin": "Latin",
    "ancient_greek": "Ancient Greek",
    "ancient_egyptian": "Ancient Egyptian",
    "old_english": "Old English",
    "old_norse": "Old Norse",
    "sanskrit": "Sanskrit",
    "akkadian": "Akkadian",
    "sumerian": "Sumerian",
    "babylonian": "Babylonian",
    "phoenician": "Phoenician",
    "aramaic": "Aramaic",
    "coptic": "Coptic",
    "elamite": "Elamite",
    "hittite": "Hittite",
    "minoan": "Minoan",
    "mycenaean": "Mycenaean",
    
    # Supernatural/Special Languages (for various supernatural templates)
    "enochian": "Enochian",
    "spirit_speech": "Spirit Speech",
    "first_tongue": "First Tongue",
    "high_speech": "High Speech",
    "animal_speech": "Animal Speech",
}
