from world.cofd.stat_types import Merit

vampire_merits = [
    Merit(
        name="Acute Senses",
        min_value=1,
        max_value=1,
        description="The vampire can see, smell, and hear at twice the distance and with twice the accuracy of an average, healthy mortal. The vampire's senses of taste and touch are also twice as sensitive. The vampire can see in pitch dark and perfectly identify any sensory stimulus she has experienced before. Add Blood Potency to any roll to use her senses. Drawback: Any exceptional success on sense rolls causes Obsession Condition for the stimulus lasting nights equal to successes.",
        merit_type="physical",
        prerequisite=""
    ),
    Merit(
        name="Altar",
        min_value=3,
        max_value=3,
        description="Your character is attuned to a mystical, bloody altar. In the presence of the altar, Acolytes may use teamwork rules when using Crúac rituals. Double the time necessary and determine time by lowest Crúac dots of the group. Allows vampires uninitiated in Crúac to participate in rituals. Drawback: Three or more characters must purchase this Merit to gain benefits, each contributing a single Merit dot.",
        merit_type="supernatural",
        prerequisite="covenant_status_circle:1"
    ),
    Merit(
        name="Anointed",
        min_value=2,
        max_value=2,
        description="Once per chapter, roll Presence + Expression when preaching to a crowd. Small clique -1 die, small crowd -2, large crowd -3. Listeners gain Raptured Condition. Drawback: Cannot use this Merit on herself.",
        merit_type="social",
        prerequisite="covenant_status_sanctum:1"
    ),
    Merit(
        name="Atrocious",
        min_value=1,
        max_value=1,
        description="Your character's monstrous Beast dominates her personality. Her threats always ring true. Any rolls to invoke the monstrous Beast gain the 8-again quality. Drawback: Does not get 10-again quality on rolls to invoke or resist seductive or competitive Beasts.",
        merit_type="social",
        prerequisite="!cutthroat,!enticing"
    ),
    Merit(
        name="Attache",
        min_value=1,
        max_value=1,
        description="Each Retainer gains any combination of Contacts, Resources, or Safe Place Merit dots equal to the vampire's Invictus Status. Drawback: Must access through intermediary, requires time and red tape navigation.",
        merit_type="social",
        prerequisite="covenant_status_invictus:1"
    ),
    Merit(
        name="Bloodhound",
        min_value=2,
        max_value=2,
        description="Your character can discern the intricacies of blood by smelling it, as if he had tasted it. When using Kindred senses to detect blood, track by blood, or pick out blood details, he only needs to smell a blood source.",
        merit_type="physical",
        prerequisite="wits:3"
    ),
    Merit(
        name="Cacophony Savvy",
        min_value=1,
        max_value=3,
        description="You have your finger on the pulse of the Kindred underground. Adept with codes and cants that allow Kindred culture to flourish. Each level builds on previous. (•) Gettin' Up: Read signs with Intelligence + Streetwise. (••) Backpacker: Know new Kindred's feeding grounds and aliases within a week. (•••) Wearing a Hat: Once per chapter, ask Storyteller questions about city affairs. Drawback: Must regularly contribute news and gossip to stay active.",
        merit_type="social",
        prerequisite="city_status:1"
    ),
    Merit(
        name="Carthian Pull",
        min_value=1,
        max_value=1,
        description="Each month, access dots of Allies, Contacts, Haven, and Herd Merits equal to Carthian Status. Drawback: These Merits are temporary and superficial. Each use is a favor that must be repaid.",
        merit_type="social",
        prerequisite="covenant_status_carthian:1"
    ),
    Merit(
        name="Claws of the Unholy",
        min_value=1,
        max_value=1,
        description="When wielding claws from Unnatural Aspect while in frenzy, weapon modifier becomes +0 aggravated. These claws ignore all armor not generated by Resilience. Drawback: Only usable while frenzied or riding the wave. Once purchased, modification is not optional.",
        merit_type="supernatural",
        prerequisite="protean:4"
    ),
    Merit(
        name="Close Family",
        min_value=1,
        max_value=1,
        description="Add +1 to all blood sympathy bonuses and apply 8-again quality to all blood sympathy rolls. Treat all relations as one step closer for sympathy distances. Drawback: When succeeding on blood sympathy roll, lose ability to spend Willpower for bonus dice for remainder of scene.",
        merit_type="supernatural",
        prerequisite=""
    ),
    Merit(
        name="Cutthroat",
        min_value=1,
        max_value=1,
        description="Your character's competitive Beast flows in her every action. Any rolls to invoke the competitive Beast gain the 8-again quality. Drawback: Does not get 10-again quality on rolls to invoke or resist monstrous or seductive Beasts.",
        merit_type="social",
        prerequisite="!atrocious,!enticing"
    ),
    Merit(
        name="Distinguished Palate",
        min_value=1,
        max_value=1,
        description="Consider any Taste of Blood roll an exceptional success with only a single success. Drawback: Choose a preferred feature in vessels comprising no more than one-tenth of population. When feeding from other sources, ignore first point of Vitae ingested per scene.",
        merit_type="supernatural",
        prerequisite=""
    ),
    Merit(
        name="Dream Visions",
        min_value=1,
        max_value=1,
        description="During the day, dreams of what's to come in vague symbols. Once per night when meeting someone new or visiting new place, make Blood Potency roll. If successful, ask one yes/no/maybe question about the person or place. Drawback: Only once per person on first meeting, once per night total.",
        merit_type="supernatural",
        prerequisite="clan:mekhet"
    ),
    Merit(
        name="Dynasty Membership",
        min_value=1,
        max_value=3,
        description="Claims membership to long-standing dynasty of Kindred. (•) New Kid: Once per chapter, add dynasty senior's Clan Status to Social dice pool. (••) Exemplar: Ignore first Door in Social engagements against those who respect/fear dynasty. (•••) Patriarch/Matriarch: Once per chapter, make demand of dynasty member who gains Tasked Condition. Drawback: Must make association known. Dynasty must have at least three members.",
        merit_type="social",
        prerequisite="clan_status:1"
    ),
    Merit(
        name="Enticing",
        min_value=1,
        max_value=1,
        description="Your character's seductive Beast oozes with ease and confidence. Any rolls to invoke the seductive Beast gain the 8-again quality. Drawback: Does not get 10-again quality on rolls to invoke or resist monstrous or competitive Beasts.",
        merit_type="social",
        prerequisite="!atrocious,!cutthroat"
    ),
    Merit(
        name="Feeding Grounds",
        min_value=1,
        max_value=5,
        description="Your character has fertile feeding grounds. Add dot rating to hunting rolls, starting Vitae rolls, and predatory aura conflicts on territory. Drawback: Territory doesn't maintain itself. Trespassers must not go uncontested.",
        merit_type="social",
        prerequisite=""
    ),
    Merit(
        name="Friends in High Places",
        min_value=1,
        max_value=1,
        description="Each month, automatically open Doors equal to status dots. Person being persuaded must be acting on behalf of organization. Drawback: Influence comes from specific Invictus member and character owes him a favor.",
        merit_type="social",
        prerequisite="covenant_status_invictus:1"
    ),
    Merit(
        name="Haven",
        min_value=1,
        max_value=5,
        description="A good haven is safe from sun and familiar. Add Haven dots to Humanity rolls to notice danger while sleeping, Stamina + Resolve rolls to remain awake, and Kindred senses rolls within. Drawback: Losing Haven is breaking point at Humanity 8 minus dot rating. Must be tied to Safe Place Merit.",
        merit_type="social",
        prerequisite="safe_place:1"
    ),
    Merit(
        name="Herd",
        min_value=1,
        max_value=5,
        description="Cultivates cliques of mortals willing and eager for the Kiss. Each week, draw Vitae equal to twice Merit's dot rating without rolls. Taking more requires normal hunting rolls. Drawback: Addicts need their fix and demand attention. Must have minor interactions before they give blood freely.",
        merit_type="social",
        prerequisite=""
    ),
    Merit(
        name="Honey Trap",
        min_value=1,
        max_value=1,
        description="When a vampire tastes your character's Vitae, she regains a point of Willpower. If this results in new bond or steps up existing bond, she also takes a Beat.",
        merit_type="supernatural",
        prerequisite=""
    ),
    Merit(
        name="Invested",
        min_value=1,
        max_value=1,
        description="Divide dots equal to Invictus status in Herd, Mentor, Resources, and Retainers Merits. Can be added to existing Merit dots. If loses Status dots, granted dots go away. Drawback: Advantages came from covenant and are subject to covenant scrutiny.",
        merit_type="social",
        prerequisite="covenant_status_invictus:1"
    ),
    Merit(
        name="Kiss of the Succubus",
        min_value=1,
        max_value=1,
        description="Kiss causes Addicted Condition in mortals as well as Swooning Condition. Drawback: Double-edged sword - keeps blood dolls coming back but they won't stay away.",
        merit_type="supernatural",
        prerequisite="clan:daeva"
    ),
    Merit(
        name="Lineage",
        min_value=1,
        max_value=1,
        description="Once per chapter, represent single dot of Allies, Contacts, Mentor, Resources, or Status that sire may have possessed. Drawback: Calling on sire's reputation taxes his social capital and he may ask for repayment.",
        merit_type="social",
        prerequisite="clan_status:1"
    ),
    Merit(
        name="Lorekeeper",
        min_value=1,
        max_value=1,
        description="When buying Library Merit, also receive dots in Retainers and Herd Merits divided however chosen. Drawback: Retainers and Herd drawn by forbidden knowledge. Must let slip information to mortal retinue to maintain advantages.",
        merit_type="social",
        prerequisite="covenant_status_sanctum:1"
    ),
    Merit(
        name="The Mother-Daughter Bond",
        min_value=1,
        max_value=1,
        description="When purchasing Mentor Merit, that Mentor is protected by True Friend Merit without having to purchase True Friend. Drawback: Mentor has stronger requirements and demands loyalty, if not monogamy.",
        merit_type="social",
        prerequisite="covenant_status_circle:1"
    ),
    Merit(
        name="Night Doctor Surgery",
        min_value=3,
        max_value=3,
        description="With hour of treatment, roll Intelligence + Medicine. Each success converts one lethal to bashing. Three successes convert one aggravated to lethal. Can make facial appearance changes over time. Drawback: Movement calls on services frequently. Cannot perform on self. Only one attempt per injury.",
        merit_type="mental",
        prerequisite="covenant_status_carthian:2"
    ),
    Merit(
        name="Speaker for the Silent",
        min_value=3,
        max_value=3,
        description="Can act as medium for torpid elder's consciousness. While possessed, Speaker is aware but torpid Kindred controls body. Torpid Kindred retains no Disciplines. Speaker can spend Willpower to eject torpid mind.",
        merit_type="supernatural",
        prerequisite="dynasty_membership:1,covenant_status_invictus:1"
    ),
    Merit(
        name="Pack Alpha",
        min_value=1,
        max_value=1,
        description="Designate coterie of Kindred and ghouls as pack. When pack takes teamwork actions, supporting characters gain 8-again quality. Removing pack member requires causing lethal damage in last three Health boxes then exiling for week. Drawback: When pack member defies you, must make example or lose Willpower point.",
        merit_type="social",
        prerequisite="clan:gangrel"
    ),
    Merit(
        name="Unnatural Affinity",
        min_value=1,
        max_value=5,
        description="Each dot allows nourishment from blood of one type of supernatural creature (werewolves, ghosts, mummies, zombies, etc.). This blood counts as Kindred Vitae for feeding restrictions. Drawback: Doesn't inherently make character more able to feed from chosen subject.",
        merit_type="supernatural",
        prerequisite=""
    ),
    Merit(
        name="Swarm Form",
        min_value=2,
        max_value=2,
        description="When taking Beast's Skin, become swarm of Size 0 or 1 animals. May perceive through any creature's senses. Swarm spreads over 5 yards per Blood Potency dot. Everyone within suffers persistent Distracted Condition. Roll attacks normally but swarm takes max 1 damage (2 on exceptional success). Can attack those within for Strength + Brawl ignoring Defense.",
        merit_type="supernatural",
        prerequisite="protean:3"
    ),
    Merit(
        name="Secret Society Junkie",
        min_value=1,
        max_value=1,
        description="When taking Status or Mystery Cult Initiation reflecting non-Kindred organizations, also gain Herd dots equal to the Merit.",
        merit_type="social",
        prerequisite="covenant_status_ordo:1"
    ),
    Merit(
        name="Sworn",
        min_value=1,
        max_value=1,
        description="Sworn to serve Ordo Dracul branch (Axe, Dying Light, or Mysteries). Gain dots equal to Covenant Status split between Mentor and Retainer Merits. Can swap between chapters. Drawback: Cannot go two nights without devoting time to covenant affairs or face punishment.",
        merit_type="social",
        prerequisite="covenant_status_ordo:1"
    ),
    Merit(
        name="I Know a Guy",
        min_value=1,
        max_value=1,
        description="Once per story, access temporary Retainer dots equal to Allies. These Retainers act in Carthian's interest. Drawback: Retainers serve Allies group's interests first. Contrary actions risk relationship with Allies.",
        merit_type="social",
        prerequisite="covenant_status_carthian:1"
    ),
    Merit(
        name="Touchstone",
        min_value=1,
        max_value=5,
        description="Each dot allows additional Touchstone. Refer to Touchstone chart for Humanity dot assignment. Drawback: Losing attachment speeds Humanity loss. If last Touchstone dies, character feels call of torpor.",
        merit_type="social",
        prerequisite=""
    ),
    Merit(
        name="Undead Menses",
        min_value=2,
        max_value=2,
        description="Once per night, produce viscous dark blood. Using this blood in Crúac ritual grants 8-again quality. Touching to person before affecting with Discipline causes Blood Potency penalty to Resistance. Drawback: Must identify as female. Multiple uses cause aggravated damage. Blood identification attempts gain +5 dice.",
        merit_type="supernatural",
        prerequisite=""
    ),
    Merit(
        name="Unsettling Gaze",
        min_value=1,
        max_value=1,
        description="When evoking monstrous Beast, if inflicting Bestial Condition with exceptional success, also force breaking point if victim has higher Humanity than yours. Drawback: Forcing breaking point in another is also breaking point for character if Humanity 3 or higher.",
        merit_type="supernatural",
        prerequisite="clan:nosferatu"
    ),
    Merit(
        name="Where the Bodies Are Buried",
        min_value=2,
        max_value=2,
        description="Times equal to Invictus Status per story, ask questions about another vampire: Who would they run to in trouble? Most frequent vessel? Main income source? Closest living family? Covered up human murder? Drawback: Investigating attracts attention from fellow Invictus.",
        merit_type="social",
        prerequisite="covenant_status_invictus:2"
    ),
    Merit(
        name="Lex Terrae",
        min_value=2,
        max_value=2,
        description="Blood poached from Feeding Ground is tainted for unauthorized Kindred. When poacher sleeps, blood dissolves. Upon waking, violently retches taking bashing damage per Vitae lost. Lips stain black for one week. Drawback: Requires clearly-defined and publicly announced feeding ground.",
        merit_type="supernatural",
        prerequisite="covenant_status_carthian:2,feeding_grounds:1"
    ),
    Merit(
        name="Mandate from the Masses",
        min_value=5,
        max_value=5,
        description="With Movement support vote, reduce enemy's Blood Potency by one dot per five total Carthian Status dots in support. If reduced to zero, becomes revenant. Drawback: Willpower dot and Blood Potency only return if victim flees city or meets Final Death.",
        merit_type="supernatural",
        prerequisite="covenant_status_carthian:5"
    ),
    Merit(
        name="Right of Return",
        min_value=2,
        max_value=2,
        description="Carthian Status doesn't count toward normal limitations on multiple Covenant Status Merits. Can have up to five dots of other Covenant Status. Treat impressions as one step better in Social Maneuvering. Drawback: Loses 10-again quality on rolls to hide suspicious behavior from other covenant members.",
        merit_type="social",
        prerequisite="covenant_status_carthian:2,city_status:1"
    ),
    Merit(
        name="Strength of Resolution",
        min_value=1,
        max_value=1,
        description="Add Carthian Status to dice pools to contest Discipline or supernatural power that would coax violation of acknowledged city law.",
        merit_type="social",
        prerequisite="covenant_status_carthian:1"
    ),
    Merit(
        name="Plausible Deniability",
        min_value=4,
        max_value=4,
        description="Attempts to use Discipline or supernatural power to prove guilt in breach of city law automatically fail. Cannot be forced to confess. Honesty detection suffers Carthian Status penalty. No diablerie aura stains. Drawback: Lose City and Carthian Status in Social rolls against witnesses who know of guilt.",
        merit_type="supernatural",
        prerequisite="covenant_status_carthian:3"
    ),
    Merit(
        name="Notary",
        min_value=2,
        max_value=2,
        description="Presides over Oath agreements. Invictus may not use Status in rolls against you. Each month, request access to single dot of Allies, Contacts, Herd, Mentor, or Resources. Drawback: If caught administering unwilling Oath or non-Invictus as liege, face Final Death.",
        merit_type="social",
        prerequisite="covenant_status_invictus:3"
    ),
    Merit(
        name="Oath of Action",
        min_value=4,
        max_value=4,
        description="Vassal swears to perform difficult service. Vassal gains access to liege's Discipline. Liege's Blood Potency increases by one. If vassal succeeds, liege takes aggravated damage equal to Discipline dots. If vassal fails or month passes, vassal takes damage. Drawback: Only one Oath of Action at a time as vassal or liege.",
        merit_type="supernatural",
        prerequisite=""
    ),
    Merit(
        name="Oath of Fealty",
        min_value=1,
        max_value=1,
        description="Vassal may draw Vitae from liege equal to Invictus Status per week. Vitae transfers mystically without addiction or bond risk. Liege always knows if vassal lies. Drawback: Vassal may only owe fealty to one liege.",
        merit_type="supernatural",
        prerequisite="covenant_status_invictus:1"
    ),
    Merit(
        name="Oath of Penance",
        min_value=3,
        max_value=3,
        description="Liege receives every tenth Vitae vassal ingests over any distance without bond risk. Vassal becomes immune to liege's Discipline effects. Drawback: While paying penance, may not gain benefits of other Oaths but retains drawbacks.",
        merit_type="supernatural",
        prerequisite=""
    ),
    Merit(
        name="Oath of Serfdom",
        min_value=2,
        max_value=2,
        description="Contract between landlord and tenant. Vassal gains dot of Celerity, Resilience, or Vigor while in granted land or defending liege. Instinctively knows when predatory aura enters territory. Liege gains vassal's Feeding Ground dots in rolls against her and immunity to blood bonds from vassal.",
        merit_type="supernatural",
        prerequisite=""
    ),
    Merit(
        name="Kindred Dueling",
        min_value=1,
        max_value=5,
        description="Fighting style for Kindred combat with edged weapons. (•) Hamstring: Target limb to deny Physical Intensity benefits. (••) Taunt: Remove dice to force frenzy roll with penalty. (•••) Carving: Weapon deals lethal to Kindred. (••••) Pincushion: Lodge weapon to prevent Vitae healing. (•••••) Spray: Sacrifice Defense to remove Vitae instead of Health.",
        merit_type="physical",
        prerequisite="composure:3,weaponry:2"
    ),
    Merit(
        name="Riding the Wave",
        min_value=1,
        max_value=5,
        description="Fighting style for using Beast while riding the wave. (•) Ravage: Fangs become 1L weapons. (••) Primal Strength: Double Strength bonus for instant strength actions. (•••) In the Zone: Willpower for riding wave gives +3 dice to actions. (••••) Unyielding: Recover Willpower spent to initiate ride after successful scene. (•••••) Animal Grace: When spending Willpower to attack or defend, gain both +2 Defense and +3 attack.",
        merit_type="physical",
        prerequisite="composure:3,resolve:3"
    ),
    # Location-based Merits
    Merit(
        name="Burrow",
        min_value=1,
        max_value=5,
        description="Replaces Haven. You share a hideout with other revenants. Add Burrow as bonus dice to stir from daysleep and stay awake in the daytime. In combat, intruders and unfamiliar guests are Distracted for one turn per dot of Burrow.",
        merit_type="social",
        prerequisite="safe_place:1"
    ),
    Merit(
        name="Mandragora Garden",
        min_value=1,
        max_value=5,
        description="Your Safe Place grows ghouled plants, which you must feed Vitae equal to your Merit dots each month, but which produce twice that quantity in Vitae's worth of sap and nectar. Their magical sympathy empowers Crúac cast there and receives it from afar, but can rile the Beast when attacked.",
        merit_type="supernatural",
        prerequisite="cruac:1,covenant_status_circle:1,safe_place:1"
    ),
    Merit(
        name="Nest Guardian",
        min_value=1,
        max_value=5,
        description="You are the custodian of a Wyrm's Nest, host to a supernatural phenomenon proportional to dots in this Merit. You may purchase additional features separately (Chapterhouse, Crucible, Feng Shui, Perilous Nest).",
        merit_type="supernatural",
        prerequisite="covenant_status_ordo:1"
    ),
    Merit(
        name="Temple of Damnation",
        min_value=1,
        max_value=5,
        description="You've secured and consecrated a gathering place to a particular Sanctified virtue. Apply dots in this Merit as a bonus to actions in service of that virtue while within the temple, or after attending rites there.",
        merit_type="supernatural",
        prerequisite="covenant_status_sanctum:1,safe_place:1"
    )
]

# Create dictionary for easy lookup
vampire_merits_dict = {merit.name.lower().replace(" ", "_").replace("(", "").replace(")", ""): merit for merit in vampire_merits}
